version: '3.5'
services:
  # proxy
  mhw_proxy:
    image: nginx:1.13
    container_name: mhw_proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/conf/conf.d:/etc/nginx/conf.d
      - ./proxy/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
      - ./proxy/log:/var/log/nginx
    environment:
      TZ: "Asia/Tokyo"
    links:
      - mhw_app
    networks:
      - app_net
    tty: true
  # database
  mhw_db:
    image: mysql:5.7
    container_name: mhw_db
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mhw
      MYSQL_USER: mhw_user
      MYSQL_PASSWORD: mhw_password
      TZ: Asia/Tokyo
    volumes:
     - ./data/db/conf.d:/etc/mysql/conf.d
     - ./mysql-storage:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_net
  # application
  mhw_app:
    build: ./data/app
    container_name: mhw_app
    command: uwsgi --ini /code/django.ini
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code
      - ./static:/static
    environment:
      TZ: Asia/Tokyo
    links:
      - mhw_db
    networks:
      - app_net
    tty: true

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default

volumes:
 data-storage:
   driver: local
